// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "wrapColumns": string;
      "wrapRows": string;
      "fontSizes": string;
      "autoFitWidthOnLoad": boolean;
      "autoFitFontOnLoad": boolean;
    };
  }
}
